# Generated by Django 4.2.16 on 2026-05-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartanalysislog',
            name='coins_charged',
        ),
    ]
