# Generated by Django 4.2.16 on 2026-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_initial_tv_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewproduct',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description (optional)'),
        ),
        migrations.AddField(
            model_name='tradingviewproduct',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name (optional)', max_length=100),
        ),
    ]
