# Generated by Django 4.2.16 on 2026-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_tv_product_i18n_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewproduct',
            name='features',
            field=models.TextField(blank=True, help_text='Mỗi dòng = 1 tính năng (Tiếng Việt). Ví dụ:\nChart real-time chuyên gia\nMACD · RSI · EMA · Supertrend'),
        ),
        migrations.AddField(
            model_name='tradingviewproduct',
            name='features_en',
            field=models.TextField(blank=True, help_text='English features, one per line. Leave blank to use Vietnamese.'),
        ),
    ]
