# Generated by Django 4.2.16 on 2026-05-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_add_tv_product_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingviewproduct',
            name='interval',
        ),
    ]
