# Generated by Django 4.2.16 on 2026-05-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_tv_product_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingviewproduct',
            name='symbol',
        ),
    ]
