# Generated by Django 4.2.16 on 2026-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_remove_tv_product_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartanalysislog',
            name='trade_status',
            field=models.CharField(blank=True, choices=[('', 'Chưa kiểm tra'), ('TP', 'Chạm TP'), ('SL', 'Chạm SL')], default='', max_length=2),
        ),
    ]
