# Generated by Django 4.2.16 on 2026-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_add_trade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_cost', models.PositiveIntegerField(default=20, verbose_name='Giá gói tuần (xu)')),
                ('month_cost', models.PositiveIntegerField(default=50, verbose_name='Giá gói tháng (xu)')),
                ('year_cost', models.PositiveIntegerField(default=400, verbose_name='Giá gói năm (xu)')),
            ],
            options={
                'verbose_name': 'Giá gói AI Trading',
                'verbose_name_plural': 'Giá gói AI Trading',
            },
        ),
    ]
