# Generated by Django 4.2.16 on 2026-05-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_add_ai_plan_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingviewproduct',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='Hiện thị giao diện "Sắp ra mắt", ẩn nút mua.', verbose_name='Chuẩn bị ra mắt'),
        ),
    ]
