# Generated by Django 4.2.16 on 2026-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_seed_okx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerlink',
            name='partner_code',
            field=models.CharField(blank=True, help_text='Mã đối tác / mã mời', max_length=100),
        ),
    ]
