# Generated by Django 4.2.16 on 2026-06-07 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_alter_brokerlink_partner_code_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerlink',
            name='register_url',
            field=models.URLField(help_text='Link đăng ký IB/affiliate', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
