# Generated by Django 4.2.16 on 2026-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_alter_brokerlink_register_url_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerlink',
            name='copy_features',
            field=models.TextField(blank=True, help_text='Tính năng copy trade (VI) — mỗi dòng 1 tính năng'),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='copy_features_en',
            field=models.TextField(blank=True, help_text='Features (EN) — one per line. Để trống = dùng bản VI.'),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='copy_trade_url',
            field=models.URLField(blank=True, help_text='Link tới trang Copy Trade của sàn (vd: https://www.bybit.com/copy-trading/)'),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='show_in_copy_trade',
            field=models.BooleanField(default=False, verbose_name='Hiện ở trang Copy Trade'),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='tag_en',
            field=models.CharField(blank=True, help_text='Badge tag (EN)', max_length=80),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='tag_vi',
            field=models.CharField(blank=True, help_text='Badge tag (VI) — vd: Đề xuất cho người mới', max_length=80),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='trader_count',
            field=models.CharField(blank=True, help_text='Số trader hiển thị — vd: 3,000+', max_length=20),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='trader_count_label_en',
            field=models.CharField(blank=True, default='Traders available', max_length=60),
        ),
        migrations.AddField(
            model_name='brokerlink',
            name='trader_count_label_vi',
            field=models.CharField(blank=True, default='Trader để chọn', max_length=60),
        ),
    ]
