# Generated by Django 4.2.16 on 2026-06-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_brokerlink_copy_trade_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradeExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sàn')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='copytrade_logos/', verbose_name='Logo sàn')),
                ('copy_trade_url', models.URLField(help_text='Link tới trang Copy Trade của sàn', verbose_name='Link Copy Trade')),
                ('register_url', models.URLField(blank=True, help_text='Link đăng ký IB/affiliate (nút Đăng Ký)', verbose_name='Link đăng ký affiliate')),
                ('tag_vi', models.CharField(blank=True, help_text='Vd: Đề xuất cho người mới', max_length=80, verbose_name='Badge tag (VI)')),
                ('tag_en', models.CharField(blank=True, max_length=80, verbose_name='Badge tag (EN)')),
                ('trader_count', models.CharField(blank=True, help_text='Vd: 3,000+', max_length=20, verbose_name='Số trader')),
                ('trader_count_label_vi', models.CharField(blank=True, default='Trader để chọn', max_length=60, verbose_name='Nhãn số trader (VI)')),
                ('trader_count_label_en', models.CharField(blank=True, default='Traders available', max_length=60, verbose_name='Nhãn số trader (EN)')),
                ('copy_features', models.TextField(blank=True, help_text='Mỗi dòng 1 tính năng', verbose_name='Tính năng (VI)')),
                ('copy_features_en', models.TextField(blank=True, help_text='Mỗi dòng 1 tính năng. Để trống = dùng bản VI.', verbose_name='Tính năng (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Copy Trade — Sàn giao dịch',
                'verbose_name_plural': 'Copy Trade — Sàn giao dịch',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='copy_features',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='copy_features_en',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='copy_trade_url',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='show_in_copy_trade',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='tag_en',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='tag_vi',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='trader_count',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='trader_count_label_en',
        ),
        migrations.RemoveField(
            model_name='brokerlink',
            name='trader_count_label_vi',
        ),
    ]
