# Generated by Django 4.2.16 on 2026-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_add_copytrade_exchange_remove_brokerlink_copytrade_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradeexchange',
            name='guide_steps',
            field=models.TextField(blank=True, help_text='Mỗi dòng 1 bước. Vd: Truy cập link và đăng nhập tài khoản', verbose_name='Hướng dẫn các bước (VI)'),
        ),
        migrations.AddField(
            model_name='copytradeexchange',
            name='guide_steps_en',
            field=models.TextField(blank=True, help_text='Mỗi dòng 1 bước. Để trống = dùng bản VI.', verbose_name='Hướng dẫn các bước (EN)'),
        ),
    ]
