# Generated by Django 4.2.16 on 2026-06-11 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_copytrade_guide_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('symbol', models.CharField(default='XAUUSD', max_length=20)),
                ('timeframe', models.CharField(default='5m', max_length=10)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tp1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tp2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tp3', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tp4', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tp5', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Đang chạy'), ('tp1', 'Chạm TP1'), ('tp2', 'Chạm TP2'), ('tp3', 'Chạm TP3'), ('tp4', 'Chạm TP4'), ('tp5', 'Chạm TP5'), ('sl', 'Chạm SL'), ('closed', 'Đã đóng')], default='active', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Ghi chú thêm (tuỳ chọn)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tín hiệu giao dịch',
                'verbose_name_plural': 'Tín hiệu giao dịch',
                'ordering': ['-created_at'],
            },
        ),
    ]
