# Generated by Django 4.2.16 on 2026-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletScanState',
        ),
        migrations.RemoveField(
            model_name='deposittransaction',
            name='memo',
        ),
    ]
