# Generated by Django 4.2.16 on 2026-05-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tradingview_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
