# Generated by Django 4.2.16 on 2026-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_tradingview_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bsc_wallet',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
