# Generated by Django 4.2.16 on 2026-05-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_bsc_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bsc_wallet',
        ),
    ]
