# Generated by Django 4.2.16 on 2026-05-16 11:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_bsc_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models._avatar_upload_to),
        ),
    ]
