# Generated by Django 4.2.16 on 2026-05-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_referral_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_coins_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
