# Generated by Django 4.2.16 on 2026-05-20 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_referral_coins_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payout_wallet',
            field=models.CharField(blank=True, help_text='Địa chỉ ví BSC (BEP-20) để nhận hoa hồng USDT', max_length=42),
        ),
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('amount_coins', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('COMPLETED', 'Hoàn tất'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
