# Generated by Django 4.2.16 on 2026-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_payout_wallet_and_referralpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_rate', models.DecimalField(decimal_places=2, default=40, help_text='Hoa hồng cấp 1 (người trực tiếp giới thiệu). Mặc định: 40%', max_digits=5, verbose_name='Tỷ lệ F1 (%)')),
                ('f2_rate', models.DecimalField(decimal_places=2, default=20, help_text='Hoa hồng cấp 2 (người giới thiệu người giới thiệu). Mặc định: 20%', max_digits=5, verbose_name='Tỷ lệ F2 (%)')),
            ],
            options={
                'verbose_name': 'Cấu hình hoa hồng',
                'verbose_name_plural': 'Cấu hình hoa hồng',
            },
        ),
    ]
